import './globals.css'

import type { Metadata } from 'next'

import { cn } from '@/lib/utils'

import { poppins } from './fonts'

export const metadata: Metadata = {
  title: 'Nowsoft',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="pt">
      <body className={cn(poppins.className, 'bg-white')}>{children}</body>
    </html>
  )
}

export default RootLayout
